version: "3.7"

services:
  app:
    build:
      context: .
    env_file:
      - .env
      - db.env
    restart: on-failure
#    volumes:
#      - ./server:/app
#      - /app/node_modules
    command: >
      /wait-for-it.sh db:3306 -- npm run start

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - db.env
    restart: on-failure
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
